vechain/vechain-kit

packages/vechain-kit/src/config/testnet.ts

Updated the config to use the correct oracle address on testnet, ensuring accurate asset balance retrieval.
Fixes #59

Fix: Asset Balance Fetch on Testnet

---

packages/vechain-kit/src/components/AccountModal/Components/AccountSelector.tsx

Truncate the domain if present to prevent UI breakage and ensure horizontal icons remain within the viewport
Please delete options that are not relevant.

Fix: Truncate domain on Account 

---

packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/ExploreEcosystemContent.tsx
packages/vechain-kit/src/hooks/api/vebetterdao/xApps/getXApps.ts

This PR updates the app fetching logic to check response for unendorsed apps which ensure compatibility with older smart contract versions that do not support endorsements.
Fixes #62
https://github.com/user-attachments/assets/5baf571c-760b-4782-b7f8-ee7e695a9b94
https://github.com/user-attachments/assets/be101447-7a2b-49b3-a37f-316e3169f802

Fix: App Fetch Compatibility for Older SC Versions

---

packages/vechain-kit/src/components/AccountModal/Contents/PrivyLinkedAccounts/PrivyLinkedAccounts.tsx
packages/vechain-kit/src/components/WalletButton/WalletButton.tsx
packages/vechain-kit/src/hooks/modals/useAccessAndSecurityModal.tsx
packages/vechain-kit/src/hooks/modals/useAccountCustomizationModal.tsx
packages/vechain-kit/src/hooks/modals/useAccountModal.tsx
packages/vechain-kit/src/hooks/modals/useChooseNameModal.tsx
packages/vechain-kit/src/hooks/modals/useConnectModal.tsx
packages/vechain-kit/src/hooks/modals/useExploreEcosystemModal.tsx
packages/vechain-kit/src/hooks/modals/useFAQModal.tsx
packages/vechain-kit/src/hooks/modals/useNotificationsModal.tsx
packages/vechain-kit/src/hooks/modals/useReceiveModal.tsx
packages/vechain-kit/src/hooks/modals/useSendTokenModal.tsx
packages/vechain-kit/src/hooks/modals/useTransactionModal.tsx
packages/vechain-kit/src/hooks/modals/useTransactionToast.tsx
packages/vechain-kit/src/hooks/modals/useWalletModal.tsx
packages/vechain-kit/src/providers/ModalProvider.tsx
packages/vechain-kit/src/providers/VeChainKitProvider.tsx

When using the `useConnectModal()` we now check if it is in in app browser (veworld) then we directly ask veworld to connect instead of showing login choices.
To accomplish this I also moved all the exported modals in a separate provider.
[ ] homepage
[ x ] vechain-kit

feat: use separate provider for exported modals + fix when opening in veworld

---

.github/workflows/deploy-gh-pages.yaml

Fix GH workflow -- add missing env variable
Fixes # (issue)
[ ] homepage
[ ] vechain-kit

add NEXT_PUBLIC_NETWORK_TYPE to gh workflow

---

packages/vechain-kit/src/hooks/api/ipfs/useIpfsImage.ts
packages/vechain-kit/src/hooks/api/ipfs/useIpfsMetadata.ts
packages/vechain-kit/src/utils/ipfs.ts

After I added this header api calls fails due to a cors error, saying: 
`Access to fetch at 'https://api.gateway-proxy.vechain.org/ipfs/bafybeif4d3uaienxhxslvpnwxwpewvrvs3egv7rvci3jet5o5v6ssibljm/media/logo.jpeg' from origin 'https://vechain-kit.vechain.org' has been blocked by CORS policy: Request header field x-project-id is not allowed by Access-Control-Allow-Headers in preflight response.`
I'm rolling back changes made in https://github.com/vechain/vechain-kit/pull/89
Reopening ticket #74 
[ ] homepage
[ x ] vechain-kit

fix/rollback x-project-id

---

packages/vechain-kit/src/hooks/api/ipfs/useIpfsImage.ts
packages/vechain-kit/src/hooks/api/ipfs/useIpfsMetadata.ts
packages/vechain-kit/src/utils/ipfs.ts

Reverts vechain/vechain-kit#93 to add the x-project-id header

Revert "fix/rollback x-project-id"

---

examples/next-template/src/app/providers/VechainKitProviderWrapper.tsx
packages/vechain-kit/src/components/AccountModal/AccountModal.tsx
packages/vechain-kit/src/components/AccountModal/Components/Tabs/Contents/AssetsTabPanel.tsx
packages/vechain-kit/src/components/AccountModal/Contents/ManageCustomToken/ManageCustomTokenContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/ManageCustomToken/index.ts
packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SelectTokenContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SendTokenSummaryContent.tsx
packages/vechain-kit/src/components/AccountModal/Types/Types.ts
packages/vechain-kit/src/components/common/AddressDisplayCard.tsx
packages/vechain-kit/src/hooks/api/utility/index.ts
packages/vechain-kit/src/hooks/api/utility/useGetCustomTokenBalances.ts
packages/vechain-kit/src/hooks/api/utility/useGetCustomTokenInfo.ts
packages/vechain-kit/src/hooks/api/wallet/useBalances.ts
packages/vechain-kit/src/hooks/api/wallet/useCustomTokens.ts
packages/vechain-kit/src/hooks/api/wallet/useRefreshBalances.ts
packages/vechain-kit/src/languages/en.json
packages/vechain-kit/src/providers/VeChainKitProvider.tsx

This PR introduces **custom token management** within the `vechain-kit`, allowing users to **add, remove, and view custom ERC-20 tokens** alongside native assets.  
Fixes #103
- **Added support for custom tokens**  
- Users can now **add ERC-20 tokens** via their contract address.  
- Existing custom tokens are **displayed with their address and symbol**.  
- Tokens are stored and persisted for better user experience.  
- **Developer Mode**  
- Now a new optional prop can be provide, `developerMode` which enables this UI to be accessed
PS: Currently it's handled by the client provider only, but could be exposed through the UI too
https://github.com/user-attachments/assets/7429d7a9-f12a-4bc4-a8e8-961e6320bc36

Feat: Custom token support

---

.github/pull_request_template.md
.github/workflows/deploy-gh-pages.yaml

- Updated the deployment workflow to deploy to vechain-kit.vechain.org on AWS for now as a fallback before we migrate vechainkit.vechain.org from GH pages to AWS
- Small update to PR template to display empty checkboxes by default

Deploy to old domain

---

.github/workflows/deploy-cloudfront.yaml
.github/workflows/deploy-gh-pages.yaml

This PR updates the deployment workflow by only deploying to AWS and removing deployment to GitHub Pages.
Closes https://github.com/vechain/vechain-kit/issues/121

Update deployment workflow

---

packages/vechain-kit/src/components/WalletButton/ConnectedWallet.tsx

This PR ensures that the connected wallet's AccountAvatar does not shrink excessively when displaying vertical images. Previously, vertical images could cause the avatar to appear distorted or too small on certain screen sizes.
[Used 200x400 placeholder image](https://placehold.co/200x400) to test the fix.
https://github.com/user-attachments/assets/23012e3b-51ee-48ee-bd6a-37e04bd7cc18
https://github.com/user-attachments/assets/145d718c-8d07-466a-bd70-e406d95a0355
Closes #172

Fix: Set Minimum Size for `AccountAvatar`

---

examples/sample-next-vechain-app/next-env.d.ts
packages/vechain-kit/src/hooks/api/utility/index.ts
packages/vechain-kit/src/hooks/api/utility/useDecodeFunctionSingature.ts

Add `useDecodeFunctionSignature` hook to get a decoded abi.Function.Definition given a signature or calldata
If calladata is provided, it attempts to decode the encoded parameters as well.
It depends only on thor-devkit for encode/decode functionalities, signature lookup is done with API calls using different providers with 3 total fallbacks
No integration test in dApp, but tested it on veworld directly
```
* // Decode a token transfer calldata
* const result = await decodeFunction("0xa9059cbb000000000000000000000000ab5801a7d398351b8be11c439e05c5b3259aec9b0000000000000000000000000000000000000000000000000de0b6b3a7640000");
* // Result: { definition: {...}, humanName: "transfer(to: 0xab5801a7d398351b8be11c439e05c5b3259aec9b, value: 1000000000000000000)", decodedParams: [...] }
*/
```
```
* …
```

feat(hooks): add useDecodeFunctionSignature

---

packages/vechain-kit/src/hooks/api/vetDomains/useGetAvatar.ts
packages/vechain-kit/src/hooks/api/vetDomains/useGetAvatarLegacy.ts

Sometimes, when using the testnet version of VET Domains to fetch a user's avatar, a CORS error may occur due to restrictions on allowed origins in the API. To ensure developers and users can still test avatar resolution reliably, I’ve implemented a fallback mechanism.
The `getAvatar` logic now follows this flow:
1. **Primary**: Attempt to fetch the avatar from VET Domains.  
2. **Fallback 1**: If the VET Domains request fails or returns `null`, try fetching the avatar directly from the user's `avatar` text record.  
3. **Fallback 2**: If both the above attempts fail, fall back to a default Picasso avatar.
This ensures that as long as at least one method resolves the avatar successfully, the user experience remains uninterrupted , even in environments where CORS issues may occur with the …

Fix: Add fallback for `getAvatar` fetch

---

packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameSummaryContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Profile/Customization/CustomizationSummaryContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SendTokenSummaryContent.tsx
packages/vechain-kit/src/components/ConnectModal/Components/DappKitButton.tsx
packages/vechain-kit/src/components/EcosystemModal/EcosystemContent.tsx
packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts
packages/vechain-kit/src/hooks/login/useLoginWithVeChain.ts
packages/vechain-kit/src/hooks/transactions/useSendTransaction.ts
packages/vechain-kit/src/hooks/transactions/useTransferERC20.ts
packages/vechain-kit/src/hooks/transactions/useTransferVET.ts
packages/vechain-kit/src/utils/StringUtils.ts
packages/vechain-kit/src/utils/handlePopupError.ts

- introduce `isRejectionError` util to standardise rejection error checks
- update error handling in various components to utilize the new util
Closes #215 

centralise error handling for user rejections

---

packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameSearchContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameSummaryContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Profile/Customization/CustomizationContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Profile/Customization/CustomizationSummaryContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SendTokenContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SendTokenSummaryContent.tsx
packages/vechain-kit/src/components/ConnectModal/Components/DappKitButton.tsx
packages/vechain-kit/src/components/EcosystemModal/EcosystemContent.tsx
packages/vechain-kit/src/hooks/api/vetDomains/useUpdateTextRecord.ts
packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts
packages/vechain-kit/src/hooks/login/useLoginWithVeChain.ts
packages/vechain-kit/src/hooks/transactions/useSendTransaction.ts
packages/vechain-kit/src/hooks/transactions/useTransferERC20.ts
packages/vechain-kit/src/hooks/transactions/useTransferVET.ts
packages/vechain-kit/src/types/mixPanel.ts
packages/vechain-kit/src/utils/StringUtils.ts
packages/vechain-kit/src/utils/handlePopupError.ts
packages/vechain-kit/src/utils/mixpanelClientInstance.ts

- rm unused useEffect hooks causing duplicate tracking
- improve error handling in onError callbacks to include error details
- updat `dropOff` method to accept reason and error params
- add handleClose and handleBack functions in customization and name selection flows to track modal interactions
Closes #214 

Analytics: drop-off handling and error reporting

---

packages/vechain-kit/package.json
yarn.lock

Bumped privy sdk to latest version. Had to manually install a peer dependency (cosmos/web3js) even if we are not using it.

feat: bump privy sdk

---

packages/vechain-kit/src/hooks/transactions/useSendTransaction.ts

By default we return `waitingConfirmation` because we have a txid, so it means the tx is broadcasted (even if the receipt is not yet available). Returnin "ready" was causing UI flickering (because of modals disappearing and appearing again)

fix: transaction status when sending txs

---

packages/vechain-kit/src/components/ConnectModal/Components/LoginWithGoogleButton.tsx
packages/vechain-kit/src/components/EmailCodeVerificationModal/EmailCodeVerificationModal.tsx
packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts

Manually ask Privy to create wallet when using loginWithOAuth or loginWithEmail (currently used only for email input and lgoin with google button, but it's exported and other apps can use it as well if they have their own Privy account)
Closes #263 

fix: create wallet after login

---

packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts
packages/vechain-kit/src/types/mixPanel.ts

This PR updates our OAuth login tracking to use a consistent "oauth" value rather than mapping different providers to various login methods
Closes #265 

integrate OAuth authentication tracking under single category

---

package.json
packages/vechain-kit/package.json
packages/vechain-kit/src/components/AccountModal/Components/Tabs/Contents/index.ts
packages/vechain-kit/src/components/AccountModal/Components/Tabs/index.ts
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/AppOverviewContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/Components/CategoryFilterSection.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/Components/CategoryLabel.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/Components/CustomAppComponent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/Components/SharedAppCard.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Ecosystem/ExploreEcosystemContent.tsx
packages/vechain-kit/src/components/AccountModal/Contents/Notifications/index.ts
packages/vechain-kit/src/hooks/api/utility/useAppHubApps.ts

It looks like `tsup` package doesn't check types while building correctly.
So I've added `tsc --noEmit` to build command and fixed already existed type errors.
Closes #N/A

fix: add tsc typecheck

---

packages/vechain-kit/src/hooks/utils/index.ts
packages/vechain-kit/src/hooks/utils/useCallClause.ts
packages/vechain-kit/src/hooks/utils/useEvents.ts

useEvents is used in b3tr and it is a utility hook to get events. 
What i thought we can have it in vechain-kit to help users to use type safe event getter. 
useMultipleClausesCall is also added for calling multiple calls in batch with type safety. It is becoming more needed in b3tr as well, so that's why I added this into kit.
>[!Note]
>Not something urgent, we can include it in next release.

feat: add type safe useEvents and useMultipleClausesCall

---

packages/vechain-kit/src/components/ProfileCard/ProfileCard.tsx

Updated to display customise profile and logout when using the ProfileCard component, both contents will be closed if you try to go back
Tested using next-template
https://github.com/user-attachments/assets/8df5f68e-0d93-45e5-b754-3e20bb87839f
Closes #276 

Display cutomise and logout content for profile card

---

packages/vechain-kit/src/providers/LegalDocumentsProvider.tsx

This PR adds a fallback and removes the error throw when no context is available. Without this, some apps like https://app.stargate.vechain.org/ and https://www.betterswap.io/ would crash when accessing _Settings > General > Terms and Policies_.
The issue was that `TermsAndPrivacyAccordion` tries to use `useLegalDocuments`, but at that point there’s no context available because their `VechainKitProvider` didn’t initialize it.
https://github.com/user-attachments/assets/a483c50c-c1cf-4b6c-8c0c-f6e18c09f38d

Fix(LegalDocs): Adding Fallback for Unavailable Context - v2 

---

packages/vechain-kit/src/components/TransactionToast/TransactionToast.tsx
packages/vechain-kit/src/components/WalletButton/WalletButton.tsx
packages/vechain-kit/src/components/common/BaseModal.tsx
packages/vechain-kit/src/providers/VeChainKitProvider.tsx

In current version, theme provider is used in 4 places, 3 of them in components as wrapper and one as actual theme provider. This causes to inject scripts 4 times in any app that kit used. See below how it looks in VBD 👇🏼  To prevent this, theme provider is used only below VechainKitProvider. 
This will decrease also bundle size in any app used `kit`, I suppose.
---
this is how it looks like in example/homepage current version
and this is how it looks in preview url below

fix: use single theme provider wrapper around kit

---

packages/vechain-kit/README.md

Updated the VeChain Kit **README** to document the external packages that the library utilizes and maintains behind the scenes. 
Added a new "Contract Getters Package" section that explains how VeChain Kit leverages `@vechain/contract-getters` for standardized blockchain data fetching and `@vechain/vechain-contract-types` for TypeScript contract interfaces.

Docs: Update Readme to include `contract-getters` info
