vechain/vechain-kit

packages/vechain-kit/package.json, yarn.lock
Updated privy dependencies
[ ] homepage
[x] vechain-kit
=> feat: installed latest versions of privy packages

examples/homepage/src/app/components/features/Signing/SigningExample.tsx
Fix a broken link to message signing code example
Fixes # (issue)
[ ] homepage
[ ] vechain-kit
=> fix signing example link

packages/vechain-kit/src/components/AccountModal/Contents/ConnectionDetails/Components/NetworkInfo.tsx, packages/vechain-kit/src/hooks/api/privy/index.ts, packages/vechain-kit/src/hooks/api/privy/useFetchPrivyStatus.ts, packages/vechain-kit/src/languages/de.json, packages/vechain-kit/src/languages/en.json, packages/vechain-kit/src/languages/es.json, packages/vechain-kit/src/languages/fr.json, packages/vechain-kit/src/languages/it.json, packages/vechain-kit/src/languages/ja.json, packages/vechain-kit/src/languages/zh.json
This pull request fetches and displays the Privy status in the "Connection Details" screen. The changes include updates to the `NetworkInfo` component, hooks, and localization files in order to display this.
Issue: https://github.com/vechain/vechain-kit/issues/53
=> Include Privy Status in connection details

examples/homepage/src/app/providers/VechainKitProviderWrapper.tsx, packages/vechain-kit/README.md, packages/vechain-kit/package.json, packages/vechain-kit/src/components/AccountModal/Contents/Account/AccessAndSecurityContent.tsx, packages/vechain-kit/src/components/AccountModal/Contents/PrivyLinkedAccounts/PrivyLinkedAccounts.tsx, packages/vechain-kit/src/languages/en.json, packages/vechain-kit/src/providers/VeChainKitProvider.tsx, packages/vechain-kit/src/types/Types.ts, yarn.lock
https://github.com/user-attachments/assets/68d62947-5608-43ce-8646-96efa4ad5086
[ x] homepage
[ x] vechain-kit
=> feat: bumped privy + added wallets as login method

packages/vechain-kit/src/hooks/api/ipfs/useIpfsImage.ts, packages/vechain-kit/src/hooks/api/ipfs/useIpfsMetadata.ts, packages/vechain-kit/src/utils/ipfs.ts
Closes #74 
[ ] homepage
[ x] vechain-kit
=> feat: add x-prokect-id header

.github/ISSUE_TEMPLATE/feature-request.yml
Feature request issue can't be created rn.
The problem seems just syntax.
=> Fix feature-request.yml

examples/homepage/src/app/components/features/UIControls/UIControls.tsx, packages/vechain-kit/src/components/AccountModal/Contents/Profile/Customization/CustomizationSummaryContent.tsx, packages/vechain-kit/src/hooks/api/smartAccount/factory/useUpgradeRequired.ts, packages/vechain-kit/src/hooks/api/vetDomains/index.ts, packages/vechain-kit/src/hooks/api/vetDomains/useGetResolverAddress.ts, packages/vechain-kit/src/hooks/api/vetDomains/useUpdateTextRecord.ts, packages/vechain-kit/src/hooks/transactions/useSendTransaction.ts
Closes #112 
Before:
https://github.com/user-attachments/assets/7399219f-31f7-461d-bd78-250bca109db6
After
https://github.com/user-attachments/assets/63e45a6f-f585-4109-8f2d-3f3020c9e956
[ ] homepage
[x ] vechain-kit
=> 112 bug   avoid mobile web browsers to block popup

packages/vechain-kit/src/providers/VeChainKitProvider.tsx
Closes #107 
https://github.com/user-attachments/assets/4b74becb-2c80-4ada-a95a-49712a2c1ef2
[ ] homepage
[ x] vechain-kit
=> fix: customize wallet options

examples/homepage/src/app/pages/Home.tsx, packages/vechain-kit/src/components/AccountModal/Components/AccountSelector.tsx, packages/vechain-kit/src/components/WalletButton/ConnectedWallet.tsx, packages/vechain-kit/src/components/WalletButton/WalletDisplay.tsx
This PR updates the `WalletDisplay` and `ConnectedWallet` components to improve support for small screens. For domain names longer than 18 characters, text will be truncated on mobile. Additionally, the Account Button now adjusts its width to fit its content.  
In the example homepage, I have removed the top-right theme selector due to its lack of responsiveness.
https://github.com/user-attachments/assets/bd238adb-42d3-4236-a955-ddb1779cbcf5
Closes #175 
-  [x] homepage
=> Fix: Make Account Button Responsive on Small Screens

packages/vechain-kit/src/config/index.ts, packages/vechain-kit/src/config/mainnet.ts, packages/vechain-kit/src/config/solo.ts, packages/vechain-kit/src/config/testnet.ts, packages/vechain-kit/src/hooks/api/erc20/index.ts, packages/vechain-kit/src/hooks/api/erc20/useGetErc20Balance.ts, packages/vechain-kit/src/hooks/api/index.ts, packages/vechain-kit/src/hooks/api/wallet/useBalances.ts, packages/vechain-kit/src/utils/Constants.tsx
=> feat: add usdglo

examples/homepage/src/app/components/features/Signing/SigningExample.tsx, examples/next-template/src/app/components/features/SigningExample/SigningExample.tsx, packages/vechain-kit/src/hooks/signing/useSignTypedData.ts
Fixing the signTypedData with VeWorld mobile. Passing the signer to the request, then VeWorld will fix on their side.
Closes #195 
-  [x] next-template
-  [x] homepage
=> fix: pass signer to to veworld

.github/workflows/deploy-cloudfront.yaml, .github/workflows/deploy-preview.yaml, .github/workflows/destroy-preview-env.yaml
Workflows for creating/destroying preview environments
Closes #185 
=> Initial preview environments

.github/workflows/deploy-preview.yaml, .github/workflows/destroy-preview-env.yaml
Bug fix, the BASE_PATH was being set as the original branch name instead of the processed one
Closes #203
=> Change basepath to be processed branch name

.github/workflows/deploy-cloudfront.yaml, .github/workflows/deploy-preview.yaml, examples/homepage/next.config.js, examples/homepage/src/app/components/features/Introduction/Introduction.tsx, examples/homepage/src/app/layout.tsx
This is to fix preview environments being deployed and being able to display content from the relevant path
Closes #207
-  [x] homepage
=> Fix preview environment deployments

packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameSummaryContent.tsx
Analytics update: rm duplicate events
Closes #212 
=> chore: rm duplicate nameSelection completion

.github/workflows/deploy-api-lambda.yaml, .gitignore, lambda/.env.local.json, lambda/index.ts, lambda/package.json, lambda/samconfig.toml, lambda/template.yaml, lambda/tsconfig.json
This pull request introduces a new AWS Lambda function for retrieving social identifiers linked to a given wallet address. The changes include setting up the deployment pipeline, defining the Lambda function, and adding necessary configuration files.
Closes #134 
=> Add initial api and lambda using AWS SAM

.github/workflows/deploy-api-lambda.yaml, lambda/index.ts, lambda/samconfig.toml, lambda/template.yaml
Fix the SAM deployment for getting embedded wallet details
Lambda function returns single JSON object with signin methods
=> Fix Get Embedded Wallet Details SAM deployment

packages/vechain-kit/src/utils/Constants.tsx
Add evearn as login method
https://github.com/user-attachments/assets/949ed998-986f-4241-a4c5-1568734b7f3a
=> feat: add evearn as login method

.github/workflows/deploy-api-lambda.yaml
Update SAM deployment to Osaka (ap-northeast-3)
=> Update SAM deployment to Osaka

.github/workflows/deploy-api-lambda.yaml
Update the SAM deployment workflow to trigger when the workflow file is changed
=> Trigger when workflow changes on main

packages/vechain-kit/src/components/AccountModal/Contents/Profile/Customization/CustomizationSummaryContent.tsx, packages/vechain-kit/src/components/AccountModal/Contents/SuccessfulOperation/SuccessfulOperationContent.tsx, packages/vechain-kit/src/components/UpgradeSmartAccountModal/Contents/SuccessfulOperationContent.tsx, packages/vechain-kit/src/components/common/AccountAvatar.tsx, packages/vechain-kit/src/hooks/api/vetDomains/useUpdateTextRecord.ts, packages/vechain-kit/src/hooks/api/wallet/useWalletMetadata.ts
Aligning how image is fetched and ensure that query is refetched correctly
=> feat: fix avatr fetch

.github/workflows/deploy-api-lambda.yaml, lambda/template.yaml
Updated SAM template file to include dedicated api domain name
Closes #249 
=> Add api domain name

packages/vechain-kit/package.json, packages/vechain-kit/src/components/AccountModal/Components/QuickActionsSection.tsx, packages/vechain-kit/src/components/AccountModal/Contents/ChooseName/ChooseNameSearchContent.tsx, packages/vechain-kit/src/components/AccountModal/Contents/SendToken/SendTokenContent.tsx, yarn.lock
Do not allowing uppercase in domain names. Using this ens package for an extra layer of security in normalizing the domain name.
=> fix: normalize domain name (do not allow uppercase)

.github/workflows/deploy-cloudfront.yaml
Updated workflow to copy docs and images to vechainkit.vechain.org
=> Copy docs and images from dedicated bucket

packages/vechain-kit/package.json
=> chore(release): v1.8.3

packages/vechain-kit/package.json
=> chore(release): v1.8.4

packages/vechain-kit/package.json
=> chore(release): v1.8.5

packages/vechain-kit/package.json
=> chore(release): v2.0.0-rc.4

packages/vechain-kit/package.json
=> chore(release): v2.0.0-rc.5

packages/vechain-kit/package.json
=> chore(release): v2.0.0-rc.6

.github/workflows/test-e2e.yaml, package.json, packages/vechain-kit/src/components/AccountModal/Components/AccountSelector.tsx, packages/vechain-kit/src/components/AccountModal/Components/QuickActionsSection.tsx, packages/vechain-kit/src/components/AccountModal/Contents/Account/SettingsContent.tsx, packages/vechain-kit/src/components/AccountModal/Contents/KitSettings/ChangeCurrencyContent.tsx, packages/vechain-kit/src/components/AccountModal/Contents/KitSettings/GeneralSettingsContent.tsx, packages/vechain-kit/src/components/common/AddressDisplay.tsx, packages/vechain-kit/src/hooks/api/wallet/useWallet.ts, packages/vechain-kit/src/hooks/cache/useCrossAppConnectionCache.ts, packages/vechain-kit/src/hooks/cache/useLocalStorage.ts, packages/vechain-kit/src/hooks/notifications/useNotifications.ts, packages/vechain-kit/src/hooks/utils/useAppHubApps.ts, packages/vechain-kit/src/hooks/utils/useCurrency.ts, packages/vechain-kit/src/hooks/utils/useFeatureAnnouncement.ts, packages/vechain-kit/src/hooks/utils/useIsPwa.ts, packages/vechain-kit/src/providers/LegalDocumentsProvider.tsx, packages/vechain-kit/src/providers/ModalProvider.tsx, packages/vechain-kit/src/providers/PrivyCrossAppProvider.tsx, packages/vechain-kit/src/providers/VeChainKitProvider.tsx, packages/vechain-kit/src/providers/VechainKitThemeProvider.tsx, packages/vechain-kit/src/utils/constants.tsx, packages/vechain-kit/src/utils/index.ts, packages/vechain-kit/src/utils/legalDocumentsUtils.ts, packages/vechain-kit/src/utils/mixpanelClientInstance.ts, packages/vechain-kit/src/utils/ssrUtils.ts, tests/e2e/models/HomePage.ts
=> chore: access window object keys via SSR-safe util

packages/vechain-kit/package.json
=> chore(release): v2.0.0-rc.10

.github/workflows/deploy-preview.yaml, .github/workflows/destroy-preview-env.yaml
Preventing possible template injection in workflows
-   [ ] vechain-kit
=> Fix template injection in GHA

packages/vechain-kit/package.json
* Add missing tag flag by @mikeredmond in https://github.com/vechain/vechain-kit/pull/425
* fix: sync internal theme with vechain-kit dark mode prop by @akgunberk in https://github.com/vechain/vechain-kit/pull/429
**Full Changelog**: https://github.com/vechain/vechain-kit/compare/2.0.0-rc.13...2.0.0-rc14
=> chore(release): v2.0.0-rc.14

packages/vechain-kit/package.json, yarn.lock
=> chore(release): v2.0.0-rc.15
